### ISSUE TITLE
You cannot call a method on a null-valued expression: If Cluster-InfoLevel -gt 2

### ISSUE THREAD

**Issue by ClaudiuSchuster** [AsBuiltReport/AsBuiltReport.VMware.vSphere#86] opened 2021-02-17 09:45 UTC
Hi,

if i set my Cluster Info Level on a VCSA 7 running on pwsh 7.12 to higher then 2 i get this:
`New-AsBuiltReport: You cannot call a method on a null-valued expression.`
(After a Cluster Verbose-Line Like '... AdmissionControl ...', sry i did not captured it on my tests)

The vCenter (VCSA) has 'empty' Clusters configured (without Hosts), probably this is the reason i thought....

Best Regards

**Comment by tpcarman** [comment] 2021-03-04 22:48
Hi @ClaudiuSchuster,
Given that you're seeing the 'Admission Control' message in the verbose output, this would indicate that you're having the issue on a cluster which is populated *with* hosts. Are you able to run it again with verbose output and capture the output?
Also, try using PowerShell 5.1, we don't officially support PowerShell 7 yet.

**Comment by tpcarman** [comment] 2021-03-04 23:17
I've tested with PowerShell 7.1.2 in my lab and cannot reproduce the issue with an empty cluster. I've tested with all Admission Control settings.

_Note: The vSphere report will fail on ESXi host reporting with PowerShell 7_

![image](https://user-images.githubusercontent.com/15333667/110043602-cbf27700-7d9b-11eb-9dc4-a2842ea82dda.png)

**Comment by tpcarman** [comment] 2021-09-15 21:50
As I have not had a response I will now close this issue. Please reopen this issue and provide more information if the problem persists.

**Closed by tpcarman** 2021-09-15 21:50 UTC
